README.md
Without having previously set `config --set channel_priority strict` the install for xtensor will resolve to the `conda-forge` package due to the higher version number `xtensor-0.21.5`
=> README.md: Force --strict-channel-priority on xtensor install

quetz/auth_github.py
Rather than appending a hardcoded route to a URL set in the config.
=> Perform a URL lookup for the authorize route

quetz/auth_github.py, quetz/main.py
Allow the web application to serve either the new frontend if available
or the static index.html.
=> Redirect to the root after auth/logout

quetz_client/meta.yaml
Host depending on python doesn't ensure pip is available, for
example if 'add_pip_as_python_dependency' is disabled in conda
config. Update to 'host' instead of 'build' as targeting
conda-build 3, pre-process selectors for noarch packages should
also not be used.
conda-smithy explicitly sets this to false by default in it's conda-forge feedstock package builds, see
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_linux#L7 
See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#architecture-independent-packages for the `Warning` about pre-process selectors on noarch
=> quetz_client/meta.yaml: Ensure compatibility for conda-build 3+

README.md
Description
--
The current tutorial in Readme is broken
``` bash
$ uvicorn quetz.main:app --reload
...
RuntimeError: Directory 'channels' does not exist
```
``` bash
$ ./test-cli-client.sh
./test-cli-client.sh: 2: ./test-cli-client.sh: curl: not found
```
Proposition
--
Add curl dependency 
Create channels directory
=> Fix Readme tutorial

quetz/channel_data.py, quetz/condainfo.py, quetz/dao.py, quetz/db_models.py, quetz/main.py, quetz/repo_data.py
* Split out retrieving information from an uploaded conda package
into its own class.
* Add extra fields to Package and PackageVersion database tables.
* Add retrieval functions to generate channeldata.json and repodata.json
data from the database.
* Add temporary API functionality to be able to test retrieval.
=> Add indexing information to the database

quetz/dao.py, quetz/main.py, quetz/rest_models.py, quetz_frontend/src/views/Packages.vue
This adds an initial API for pagination to the backend, and uses it in the frontend.
Also adds a search thing to the frontend and uses the `q` parameter to search in the backend.
This does break the API for `/api/channels/{}/packages` though. So I am wondering if we should activate this behind a query parameter (`&pagination=true`) or if we should give it a more generic term?
With the current API we can't know the total amount of available packages. So we should either return _all_ packages or add that value somehow.
=> add pagination and search to front- and backend for packages

quetz/auth_github.py
Fixes github auth regression introduced in #55 (missing db_url parameter to get_session()).
Thanks to @tom--pollard for spotting.
=> Fix auth regression

quetz/pkgstores.py
Remove unnecessary statement causing error using a local filesystem.
Introduces in #59 
Closes #63
=> Fix local filesystem error

quetz/indexing.py, quetz/main.py, quetz/pkgstores.py
Related to issue #63 and quick-fix proposed in PR #64.
Make localstore operations atomic:
- use a tempfile then use atomic os.rename method using @nowster snippet (thank you!)
- put main objects of add_package and add_file (which are package and file data) as first arguments, make args naming more explicit and add typing
- use local import for s3fs
I didn't introduced tests at this time, maybe we should merge as is to fix possible indexing issues and plan testing in a dedicated issue/PR.
@nowster @wolfv could you please review?
Closes #63
=> Make localstore operations atomic

README.md, quetz/auth_github.py, quetz/auth_google.py, quetz/basic_frontend/index.html, quetz/config.py, quetz/dao_google.py, quetz/main.py, quetz_frontend/src/components/Header.vue
**!!A few things to tick off before merging!!**
**The points above have been covered in the comments. For now Google Auth will be optional config, and further work will be done to integrate multi auth per user going forward**
This could be considered part of https://github.com/TheSnakePit/quetz/issues/41
=> Add Google OAuth 2.0 OpenID Connect support

README.md, quetz/cli.py
The example link for dummyuser renders (http://localhost:8000/api/dummylogin/%5B) and returns Internal Server Error. Should rather be one of the test users like alice.
=> README improvement & examples simplification

quetz/cli.py
Originally set out to improve the help messages within cli.py, ended up fixing a few other things as well.
Commits:
cli: Fix line lengths
cli: Fix 'deployement' typo
cli: Fix order of args to create()
cli: Use enum for logging levels
cli: Simplify check for non-config files
cli: Ensure errors are written to stderr
cli: Simplify create() logic a little
=> cli: General improvements

quetz/authorization.py, quetz/main.py, quetz/tests/test_auth.py
Use the same path prefix as conda for specifying a token/api-key
=> feat: prevent downloading of private channels

quetz/authorization.py, quetz/basic_frontend/index.html, quetz/cli.py, quetz/config.py, quetz/dao.py, quetz/dao_github.py, quetz/main.py, quetz/rest_models.py, quetz/tests/test_auth.py, quetz/tests/test_github_dao.py
a few fixes to streamline onboarding new users:
* allow create api keys without special privilages, this key is valid for example to post (create) new channels
* return the new key after it is created with the POST /api/api-keys method
* add a button in basic fronted to retrieve and display the key in a modal window
* also some more tests and fixes 
Notes:
* POST /api/api-keys plays two roles: creating new keys and assigning permissions, the permissions are not specific to the key but for all keys of the user
* there is no role of superadmin who by default has read/write access to all channels/packages/users
=> Onboarding create api keys

README.md, quetz/config.py, quetz/dao_github.py, quetz/pkgstores.py
tested with OVH,
sample parameters for OVH:
```
[s3]
access_key = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
secret_key = "f1f2f3f4f6f7f8f9f0a1a2a3a4a5a6a7a8"
url = "https://s3.sbg.cloud.ovh.net"
region = "sbg"
bucket_prefix="quetz-"
bucket_suffix=""
```
it also pins the authlib version because of the authlib bug: https://github.com/lepture/authlib/issues/283
=> fix s3 storage interface to work with other providers

dev_config.toml, quetz/config.py, quetz/indexing.py, quetz/main.py, quetz/mirror.py
also fixes an issue with mirror synchronisation
to configure the log level use `'[logging]` section of the config or set `QUETZ_LOG_LEVEL` env variable:
`export QUETZ_LOG_LEVEL=debug`
quetz logging messages are duplicated due to uvicron bug:
https://github.com/encode/uvicorn/issues/630
=> adding loggers

docs/source/index.rst, docs/source/qeps/index.rst, docs/source/qeps/qep-001-user-permissions.rst, quetz/authorization.py, quetz/dao.py, quetz/db_models.py, quetz/main.py, quetz/rest_models.py, quetz/tests/test_auth.py, quetz/tests/test_main.py, quetz/tests/test_mirror.py
implementation of the [QEP1](https://hackmd.io/brJub-gXSL6oXx7UoRqcQA) (part 1)
* empty
* member
* maintainer (admin)
* owner (super-admin)
=> server level user roles

.github/workflows/ci.yml, plugins/quetz_conda_suggest/README.md, plugins/quetz_conda_suggest/quetz_conda_suggest/api.py, plugins/quetz_conda_suggest/quetz_conda_suggest/db_models.py, plugins/quetz_conda_suggest/quetz_conda_suggest/main.py, plugins/quetz_conda_suggest/setup.py, plugins/quetz_conda_suggest/tests/conftest.py, plugins/quetz_conda_suggest/tests/test_main.py, plugins/quetz_conda_suggest/tests/test_quetz_conda_suggest.py, plugins/quetz_runexports/quetz_runexports/db_models.py, quetz/condainfo.py
This is without `tests` for now.
To use:
1) Create a new channel.
2) Upload some packages.
3) Hit the endpoint `/api/channels/{channel_name}/conda-suggest`
Maybe we should do creation of the `channel_suggest_map` and the `downloadable map file` as a background task?
=> add conda-suggest plugin

quetz/config.py, quetz/testing/fixtures.py
make Config a singleton class, so that we don't have to re-load the config values from the file each time the config is created
Note that for each use of Config, we  instatiate the class (`config = Config()`), which returns the singleton instance. This allows us to simply reset the instance in the tests.
=> implement singleton config

quetz/cli.py, quetz/tests/test_cli.py
Hi!
@btel @wolfv 
Seems the CLI is broken due to a database init using not required entries, thus sometimes attributes do not exist.
When passing one of the possible entries (as done in the current tests), the others are defaulting to empty lists, not causing an error.
BTW, the database init should not be done at `create` step and not `run` one ?
Calling cli command `quetz create ...` currently won't init the database.
My patch for the test fixture is maybe not ideal, I use the `pytest.mark.parametrize` decorator only to pass 1 argument/value.
Let me know if you have better ideas ;)
Thanks for your feedback!
=> Fix cli init db

quetz/cli.py, quetz/dao.py
fix to the bug: re-runing of quetz init-db would not change the permissions of exisiting or new users
this bug only occured  with sqlite and relative paths
=> fix setting permissions with init db

README.md, docs/source/using/mirroring.rst, quetz/authorization.py, quetz/condainfo.py, quetz/main.py, quetz/pkgstores.py, quetz/rest_models.py, quetz/tasks.py, quetz/tests/test_main.py, quetz/tests/test_mirror.py, quetz/tests/test_tasks.py
allow reindexing files stored in the the package store:
to reindex packages make the following request:
```
PUT /api/channels/{channel_name}/actions
```
with the body:
```
{"action": "reindex"}
```
Note 1:  the packages have to be in the path of the store that is consistent with the channel_name, for local store this would be: `{deployment_dir}/channels/{channel_name}/...`
Note 2: the channel has to be created beforehand
~~Note 3: for mirror channels you should rather use `{"action": "synchronize"}` (only for mirror_mode=mirror), the synchronisation protocol will find the files automatically in the store~~ (it's not true, you still need to reindex to get the metadata from package files, but for the moment, we don't have a way to prevent synchronisation when creating mirror channels)
=> adding re-indexing task

docs/source/using/mirroring.rst, quetz/main.py, quetz/mirror.py, quetz/rest_models.py, quetz/tasks.py, quetz/tests/test_mirror.py, quetz/tests/test_tasks.py
To re-create a mirror channel and re-index already downloaded files use `POST /api/channels` request with data:
```json
{
"name":"ORIGINAL-CHANNEL-NAME",
"private":false,
"mirror_channel_url":"ORIGINAL-URL",
"mirror_mode":"mirror",
"metadata": {
"actions": ["reindex"]}
}
```
(note that there is `reindex` under actions, but no `synchronize`)
for example:
```bash
curl -X POST "http://localhost:8000/api/channels"     \
-H  "accept: application/json" \
-H  "Content-Type: application/json"
-H  "X-API-Key: ${QUETZ_API_KEY}"
-d '{"name":"mirror-channel",
"private":false,
"mirror_channel_url":"https://conda.anaconda.org/btel",
"mirror_mode":"mirror",
"metadata": {"actions": ["reindex"]}}'
```
This request will not trigger synchronisation with the upstream server. However, you can synchronise the …
=> Disable mirror sync on demand

plugins/quetz_conda_suggest/quetz_conda_suggest/main.py, plugins/quetz_current_repodata/README.md, plugins/quetz_current_repodata/quetz_current_repodata/main.py, plugins/quetz_current_repodata/setup.py, plugins/quetz_repodata_patching/quetz_repodata_patching/main.py, plugins/quetz_repodata_patching/tests/test_main.py, quetz/hooks.py, quetz/tasks/indexing.py, quetz/utils.py
1. A new plugin `quetz_current_repodata` without an `api.py` i.e. no endpoint. Thus, it only contains the `hook`
2. The `index.html` is generated after all such `hooks` are called and the `files` parameter is updated (defined in `indexing.py`). This is different from using `pkgstore.list_files` since that would also give us data for multiple `subdirs` + would also list `packages` -- which is all extra information.
3. No tests are written for the new plugin `quetz_current_repodata` since there is no API endpoint.
4. The `quetz_conda_suggest` plugin is updated so as to use `pkgstore.add_file()` to create the `.map` file. It also updates the `index.html` so that `.map` appears in it.
=> current-repodata plugin + update conda-suggest and repodata-patching plugin

.github/workflows/ci.yml, plugins/quetz_repodata_zchunk/README.md, plugins/quetz_repodata_zchunk/quetz_repodata_zchunk/main.py, plugins/quetz_repodata_zchunk/setup.py, plugins/quetz_repodata_zchunk/tests/conftest.py, plugins/quetz_repodata_zchunk/tests/test_main.py
This PR implements partial download of the repodata using [zchunk](https://github.com/zchunk/zchunk). It should dramatically reduce repodata downloads when you already have an older repodata locally (which is the case most of the time). It will also require some work in mamba.
It's very much a work in progress, mainly to get early feedback.
=> Add repodata_zchunk plugin

.github/workflows/ci.yml, quetz/tests/test_fastfail.py
logs are quite verbose and difficult to read. This PR adds annotations to the CI jobs with the name of failed tests. This uses this pytest plugin:
https://github.com/utgwkk/pytest-github-actions-annotate-failures
=> add test reports to github action annotations

environment.yml, quetz/auth_google.py, quetz/cli.py, quetz/dao_google.py
This will align google authentication and dao with github one, and supports role assignment from the configuration.
This also prevents the `quetz create` command to fail if the directory specified exists but it's not already a deployment.
Also, I updated the httpx version in environment.yml to fix #203
=> Google auth dao

quetz/authorization.py, quetz/dao.py, quetz/main.py, quetz/tests/api/conftest.py, quetz/tests/api/test_main.py, quetz/tests/api/test_users.py
rather than deleting users we remove their profiles, identities and api keys. This allows us to keep the packages and channels, which might still be shared with others.
=> Delete user endpoint

quetz/cli.py
added this option to be able to use a single command no matter if the deployment is present or not.
With this one can:
- set a docker container with the `quetz run --skip-if-exists deployment_name` as CMD;
- place the `deployment_name` configuration in an external directory;
- run the docker with a the external directory mounted as the working directory;
- run and restart the docker without any error.
not sure if the name of the option is good, at first I thought of `--exist-ok`.
=> add --skip-if-exists to create and run commands

environment.yml, quetz/cli.py, quetz/tests/test_cli.py
This will replace the functions related to `deployments.json`
with a function that checks if a specified path is a deployment, that is:
- has a 'config.toml' file
- has a 'channels' directory
- the database specified in the config file exists.
The database existence check is performed via sqlalchemy_utils.
`quetz create` has a new `delete` option instead of the delete confirmation,
and only works if either `copy_conf` or `create_conf` is specified.
`skip_if_exists` is renamed to `exists_ok`, also.
`config_file_name` is removed from both `run` and `create` commands,
`config.toml` is the only allowed config file name.
file specified in `copy_conf` will be renamed to `config.toml` in the deployment directory.
Pathlib objects are used extensively.
we also use a context manager …
=> remove deployments.json from CLI

quetz/auth_github.py, quetz/auth_google.py, quetz/config.py, quetz/main.py, quetz/tests/test_auth_github.py, quetz_frontend/src/components/Header.vue
- the github part of the config is now optional;
- two new test endpoint to check if the google/github auth is enabled;
- Vue frontend checks for these endpoints to show the login buttons;
- using the router prefix instead of declaring the full path for each entrypoint
- minor refactors
I'm sorry I didn't add unit tests, but I cannot wrap my head around the config object...  How do I create a test config with the google entries (and without the github ones)?
=> make github login optional, frontend login buttons

quetz/main.py, quetz/tests/api/test_api_keys.py, quetz/utils.py
closes #231
Please note that the key format is not validated in `ApiKey` db or rest model in order to not break existing tests and old keys.
=> generate alphanumeric api keys

plugins/quetz_transmutation/quetz_transmutation/api.py, plugins/quetz_transmutation/tests/test_main.py, quetz/jobs/models.py, quetz/jobs/runner.py, quetz/migrations/versions/794249a0b1bd_adding_jobs_tables.py, quetz/tests/test_jobs.py
Needs some extra testing!
Example package spec:
```
"my-package>=0.1.2,<0.2,other-package==1.1"
```
which will run the job for packages:
* `my-package` with version between 0.1.2 and 0.2
* `other-package` in version 1.1
Note OR (`|`) not yet supported.
* conda:
- MatchSpec (docstring): https://github.com/conda/conda/blob/aed799b56d9ee16a3653928527e2af6e41394e85/conda/models/match_spec.py#L73
- parsing: https://github.com/conda/conda/blob/aed799b56d9ee16a3653928527e2af6e41394e85/conda/models/match_spec.py#L569
- conda docs: https://github.com/conda/conda/blob/aed799b56d9ee16a3653928527e2af6e41394e85/docs/source/user-guide/concepts/pkg-specs.rst#package-match-specifications
* PEP440: https://www.python.org/dev/peps/pep-0440/#version-scheme
=> adding query syntax

plugins/quetz_conda_suggest/quetz_conda_suggest/main.py, plugins/quetz_current_repodata/quetz_current_repodata/main.py, plugins/quetz_current_repodata/tests/test_current_repodata.py, plugins/quetz_repodata_patching/quetz_repodata_patching/main.py, plugins/quetz_repodata_zchunk/quetz_repodata_zchunk/main.py, quetz/hooks.py, quetz/pkgstores.py, quetz/tasks/indexing.py, quetz/utils.py
This should make our repodata updates safer, and also make sure that we don't have unpatched repodata in the final destination. 
@btel do you have any remarks?
=> write to tempdir before moving repodata to final destination

docs/source/using/mirroring.rst, environment.yml, quetz/condainfo.py, quetz/main.py, quetz/rest_models.py, quetz/tasks/common.py, quetz/tasks/mirror.py, quetz/tests/api/test_channels.py, quetz/tests/api/test_main_packages.py, quetz/tests/test_mirror.py
use `synchronize_repodata` action to trigger synchronisation based on repodata (no extraction of tarballs required). it's also a default when creating a new mirror channel.
=> fill db from channeldata/repodata

quetz/rest_models.py
the actions descriptions are only rendered in redoc doc:
=> adding docs for available actions

quetz/jobs/api.py, quetz/jobs/runner.py, quetz/tests/test_jobs.py
adding PUT /jobs/{} endpoint to run the job on new packages.
re-running on all packages (the processed ones included) is not yet implemented, but it could be done if a new job with the same specs is created.
=> re-running job on new package versions

plugins/quetz_transmutation/quetz_transmutation/api.py, plugins/quetz_transmutation/quetz_transmutation/jobs.py, plugins/quetz_transmutation/setup.py, quetz/cli.py, quetz/dao.py, quetz/jobs/api.py, quetz/jobs/runner.py, quetz/testing/fixtures.py, quetz/tests/data/dummy-plugin/quetz_dummyplugin-1.0-py3.egg-info/PKG-INFO, quetz/tests/data/dummy-plugin/quetz_dummyplugin-1.0-py3.egg-info/entry_points.txt, quetz/tests/data/dummy-plugin/quetz_dummyplugin/jobs.py, quetz/tests/test_jobs.py
you can create a new job, by POST /jobs endpoint. For example, to trigger new transmutation job:
```bash
curl -X POST localhost:8000/api/jobs \
-H "X-api-key: ${QUETZ_API_KEY}" \
-d '{"items_spec": "*", "manifest": "quetz-transmutation:transmutation"}'
```
to run a job on new packages:
```
curl -X PATCH localhost:8000/api/jobs/1 \
-H "X-api-key: ${QUETZ_API_KEY}" \
-d '{"status": "pending"}'
```
to run on all packages (already processed ones and new):
```
curl -X PATCH localhost:8000/api/jobs/1 \
-H "X-api-key: ${QUETZ_API_KEY}" \
-d '{"status": "pending", "force": true}'
```
Note that the runnable jobs need to be exported from plugin using the `quetz.jobs` entry point. This is to prevent an arbitrary function to be run by a malicious request.
see also #294
=> create any jobs from /jobs endpoint

dev_config.toml, docs/source/deploying/configuration.rst, quetz/cli.py, quetz/dao.py, quetz/dao_github.py, quetz/dao_google.py, quetz/tests/test_auth_github.py, quetz/tests/test_cli.py
*  provider has to be specified with each user in config `[users]` section, for example:
```
[users]
owner = ["github:username"]
```
* to assign roles defined in the config, you will need to re-run `quetz init-db` **after** the user has associated their account with quetz
* only a single identity is allowed to be associated with a username, more identities can be associated with the same user by changing directly data in the db, but due to security concerns this is not exposed with the api
closes #292
=> fix creating users with multiple providers

environment.yml, plugins/quetz_dictauthenticator/quetz_dictauthenticator/__init__.py, quetz/authentication/auth_dao.py, quetz/authentication/base.py, quetz/authentication/github.py, quetz/authentication/google.py, quetz/authentication/oauth2.py, quetz/authentication/pam.py, quetz/authorization.py, quetz/main.py, quetz/tests/authentification/test_auth_dao.py, quetz/tests/authentification/test_pam.py
note that PAM requires root-permissions (or setuid-root) to check the password for users different than the current one. This is due to the fact that PAM needs an access to read-protected /etc/shadow file that contains users' password hashes.
From pam_unix man page:
> A helper binary, unix_chkpwd(8), is provided to check the user's password when it is stored in a read protected database. This binary is very simple and will only check the password of the user invoking it. It is called transparently on behalf of the user by the authenticating component of this module. In this way it is possible for applications like xlock(1) to work without being setuid-root. The module, by default, will temporarily turn off SIGCHLD handling for the duration of execution of the helper binary. This is …
=> Add PAM authenticator

quetz/tasks/workers.py
**Update**: the problem with the solution here, is that we can launch unlimited number of workers, which would deplete server's resources. it would be best to have a queue and a fixed number workers that can spawn subprocesses, wait until they are done and tear them down after the job is finished. Similar to what is implemented in rq. Or we could switch completely to rq (BTW quetz rq adapters are not supported with the jobs framework).
related to #332 
* trigger generate_indexes action
* watch memory consumption with htop
* try running with and without plugins (both are leaking)
* use tracemalloc
* modify code to return early from the action function
* test with synchronous actions (wait for results, better but still leaking)
there are a couple of memory-related issues:
- workers stay …
=> fix memory leak in actions

quetz/pkgstores.py, quetz/tests/test_pkg_stores.py
since deletions/additions may not be immediately visible on s3, we need to retry sometimes.
AWS S3 has strong consistency since recently: https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/
OpenStack Swift (the backend behind OVH S3) has eventual consistency:
https://julien.danjou.info/openstack-swift-consistency-analysis/
=> retry removing S3 channels on error

quetz/tasks/workers.py
inspired by rq's worker implementation: https://github.com/rq/rq/blob/fc7940c77b69704ad6c059385fd530c850e5f0be/rq/worker.py#L741
SubprocessWorker has following deficiencies:
- unlimited number or workers can be launched in parallel and so there is no way to manage the server ressources
- actions are fire-and-forget so we (users and admins) never learn about possible exceptions during the executions, maybe logging them would be a step forward
This PR addresses the first one.
=> fork worker for executing task

quetz/jobs/runner.py, quetz/tests/api/conftest.py, quetz/tests/api/test_channels.py, quetz/tests/api/test_main_packages.py, quetz/tests/api/test_metrics.py, quetz/tests/conftest.py, quetz/tests/test_jobs.py, quetz/tests/test_mirror.py, quetz/tests/test_tasks.py, quetz/tests/test_versionorder.py
since #364 check_status is no longer required - workers update themselves the task/job status
=> remove check_status from job watch

plugins/quetz_harvester/tests/conftest.py, plugins/quetz_harvester/tests/test_main.py, plugins/quetz_transmutation/README.md, plugins/quetz_transmutation/tests/conftest.py, plugins/quetz_transmutation/tests/test_main.py, quetz/authorization.py, quetz/cli.py, quetz/deps.py, quetz/jobs/api.py, quetz/jobs/models.py, quetz/jobs/runner.py, quetz/tasks/workers.py, quetz/tests/test_jobs.py, quetz/tests/test_workers.py
* create a class for monitoring jobs (supervisor), which replaces run_tasks, run_jobs etc methods
* add an option to start the supervisor in a subprocess when starting quetz
* use job owner to authorize actions/tasks
=> Refactor supervisor

quetz/dao.py, quetz/jobs/api.py, quetz/jobs/handlers.py, quetz/jobs/rest_models.py, quetz/jobs/runner.py, quetz/rest_models.py, quetz/tasks/common.py, quetz/testing/mockups.py, quetz/tests/test_jobs.py
* periodic job (it will re-run on all matching package versions each time)
```
curl -X POST localhost:8000/api/jobs  -d '{"items_spec": "test-package", "manifest": "quetz-transmutation:transmutation", "repeat_every_seconds": 20}' -H "X-api-key: ${QUETZ_API_KEY}"    
```
* delayed job
```
curl -X POST localhost:8000/api/jobs -d '{"items_spec": "test-package", "manifest": "quetz-transmutation:transmutation", "start_at": "2021-03-03T11:27"}'  -H "X-api-key: ${QUETZ_API_KEY}"    
```
* we don't  store any more pickled function in the db, just the name of the function (and plugin if not a builtin function)
=> Schedule params jobs endpoint

quetz/jobs/runner.py, quetz/tests/test_jobs.py
small fix to properly reset all jobs/tasks after supervisor is restarted,
=> set tasks status to failed after restart

.github/workflows/ci.yml, plugins/quetz_harvester/README.md, plugins/quetz_harvester/quetz_harvester/jobs.py, plugins/quetz_harvester/quetz_harvester/main.py, plugins/quetz_harvester/setup.py, plugins/quetz_harvester/tests/conftest.py, plugins/quetz_harvester/tests/test_main.py, quetz/jobs/rest_models.py
* remove harvest api endpoint
* register quetz.jobs entrypoint (which allows to run the jobs using quetz /jobs endpoint)
* use the testworker for testing (which simplifies and speeds up running tests)
example:
```
curl -X POST localhost:8000/api/jobs    -H "X-api-key: ${QUETZ_API_KEY}"   \
-d '{"items_spec": "test-package", "manifest": "quetz-harvester:harvest"}' 
```
=> Update harvester plugin

environment.yml
Sqlalchemy has recently released version 1.4. This results in an
import error:
```
$ quetz run test_quetz --copy-conf ./dev_config.toml --dev --reload
Traceback (most recent call last):
File "/export/scratch1/hendriks/miniconda3/envs/quetz/bin/quetz", line 33, in <module>
sys.exit(load_entry_point('quetz', 'console_scripts', 'quetz')())
File "/export/scratch1/hendriks/miniconda3/envs/quetz/bin/quetz", line 25, in importlib_load_entry_point
return next(matches).load()
File "/export/scratch1/hendriks/miniconda3/envs/quetz/lib/python3.8/importlib/metadata.py", line 77, in load
module = import_module(match.group('module'))
File "/export/scratch1/hendriks/miniconda3/envs/quetz/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, …
```
=> set upper bound for sqlalchemy dependency

quetz/pkgstores.py
With fsspec 0.9.0, running `http http://localhost:8000/get/mychannel/noarch/repodata.json` returned:
```
http: error: ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```
Error raised on the server:
```
File "/Users/benjaminbertrand/Dev/conda/quetz/quetz/main.py", line 1600, in iter_chunks
data = fid.read(chunk_size)
ValueError: read of closed file
```
The issue is explained here: https://github.com/intake/filesystem_spec/issues/607
> However, when you select the f attribute and forget the original LocalFileOpener, the latter gets garbage-collected. This didn't used to matter, but now the superclass IOBase calls close - which closes the underlying file too.
The current fix works with fsspec …
=> Fix read of closed file with fsspec 0.9.0

docs/source/deploying/authenticators.rst, quetz/authentication/gitlab.py, quetz/basic_frontend/index.html, quetz/config.py, quetz/frontend.py, quetz/main.py, quetz_frontend/src/components/Header.vue
This PR adds GitLab as authenticator.
I realise I should have created an issue before to make this PR. This is something I need because we gonna try to deploy this internally.
I think this authenticator can be quite useful because it's quite common to have a self-hosted GitLab instance.
I didn't see any test for the GitHub or google authenticators, so there are none in this PR (it depends on the oauth2 one).
I tested the authentication manually both with gitlab.com and a self-hosted GitLab instance.
=> Add gitlab authenticator

.github/workflows/docker-build-push.yml, .github/workflows/docker-build.yml, Dockerfile
I know there is a Dockerfile under the docker directory, but it is for development.
This Dockerfile is intended more for production. It builds an image with both the frontend and conda environemnent using a multi-stages build to keep the final image size small.
I also added a GitHub workflow to build and push the image:
- The image `mambaorg/quetz:latest` is built and pushed for every commit to the master branch.
- When pushing a tag, the image is tagged with it (`mambaorg/quetz:<tag>`).
- For PR, the image is only built, but not pushed.
For the workflow to work, the `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` secrets shall be defined for the repository.
=> Add Dockerfile and GitHub Workflow

quetz/frontend.py
I noticed a security bug where Quetz will serve files outside of the quetz directory including root directories. Example(number of ".." may vary on your instance):
`curl --path-as-is http://quetzserver:8000/../../../../../../../../../../../../etc/passwd`
Returns my /etc/passwd file.
I was able to patch this on my instance by modifying quetz/frontend.py to handle the case where a relative path was given to static(), but I am not sure this is the best fix or a comprehensive solution.
=> Don't serve relative paths.

quetz/frontend.py
This will use `os.path.commonpath` to ensure any static files being served are under `frontend_dir`. Currently we are just checking for `..` in the filename (see  #395), which should work, but this methods utilizes the `os.path` library which should provide a cleaner/more robust solution, addressing #396.
=> Serve only files below frontend_dir using os.path.commonpath

quetz/frontend.py
We're moving the jupyter lab based frontend to a plugin that ships it's own backend helpers. 
This will also give additional freedom to other frontend implementers.
Here is the frontend repo: http://github.com/mamba-org/quetz-frontend
PS: @stevenryoung I am curious what frontend you were using so far? Would be happy to assist you in moving to the new one, or hearing your experiences.
=> clean up frontend.py and move lab-specific stuff to quetz-frontend extension

quetz/dao.py, quetz/main.py, quetz/rest_models.py, quetz/tests/api/test_channels.py
This PR allows the user to change the channel ttl.
The default value of 10 hours sounds a bit high to me, but it's not a big issue if it can be changed.
=> Allow to change the channel ttl

plugins/quetz_conda_suggest/quetz_conda_suggest/api.py, quetz/config.py, quetz/main.py, quetz/pkgstores.py, quetz/tasks/mirror.py, quetz/tests/test_mirror.py, quetz/tests/test_pkg_stores.py
This is an attempt to improve performances when using LocalStore by letting nginx serve static files.
If `redirect_static_files` is set to `true`, quetz will return a redirect for:
- files in the cache (cached packages from proxy channels)
- files from local channels when using LocalStore
In this case, Nginx (or something else) is expected to take care of this redirect.
I tested by deploying Nginx with something like that:
```
upstream quetz {
server 127.0.0.1:8000;
}
server {
listen      8080;
add_header  Cache-Control $control;
server_name  localhost;
location / {
proxy_set_header Host $http_host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection …
```
=> Add option to redirect static file download

quetz/main.py
As far as I can see, the serve_path function doesn't contain any async method.
When using blocking operation, the function shouldn't be defined as async.
See https://fastapi.tiangolo.com/advanced/custom-response/?h=stream#using-streamingresponse-with-file-like-objects
When trying to access the API at the same time as downloading files from quetz, I got very poor response time.
I think this is because serve_path was blocking the event loop.
With this change, I get much better results.
=> Remove async from serve_path

docker-compose.yml, docker/docker_config.toml, docker/nginx.conf, docs/source/deploying/configuration.rst, docs/source/deploying/index.rst, docs/source/deploying/nginx.rst, quetz/main.py, quetz/pkgstores.py
- Serve all files with Nginx when using LocalStore (including `repodata.json`)
- Add nginx config to docker-compose for local testing
- Add documentation about nginx configuration
I think serving json files with Nginx when it is already configured for channels makes sense as it can compress json files and add max-age to the cache-control header (as shown in the example and documentation). The only drawback I see is that the `max-age` will be the same for all channels. It has to be hard-coded in Nginx configuration and can't be set to the channel ttl.
This is only enabled for the LocalStore as Nginx needs to be configured. Maybe it should be enabled via a different option so it can be used when using another package store?
=> Add documentation about Nginx for static file redirect

quetz/pkgstores.py, quetz/tasks/mirror.py, quetz/tests/test_mirror.py
If several clients try to download the same file from a proxy channel in parallel, that file is currently downloaded several times.
This is quite inefficient and adds extra load on the remote repo.
To prevent this and ensure the file is only downloaded once, we added a lock. Other clients will wait while the file is downloaded by the first request.
=> Prevent remote files to be downloaded several times in parallel

quetz/authorization.py
Description
---
The session may contain a `user_id` that is not in the database anymore.
Make `assert_user` catch this case
Related to https://github.com/mamba-org/quetz/issues/429
=> Make `assert_user` check that user exists in db

quetz/cli.py, quetz/frontend.py, quetz/jobs/rest_models.py, quetz/main.py, quetz/tests/test_cli.py, quetz/tests/test_jobs.py
Description
---
fix tests using `alembic` 1.7
use `importlib` to load `entry_points`
remove use of `pkg_resources` to be consistent with `alembic` internal implementation
rename `dummy_plugin` fixture to `dummy_job_plugin` to be more explicit
rename `entry_points` fixture to `dummy_migration_plugin`
refactor `dummy_migration_plugin` to mock a package and its `entry_points`
=> Compatibility with `alembic` 1.7

docs/source/deploying/configuration.rst, quetz/config.py, quetz/main.py
Implementation of #445 . This PR adds the configurable ability for the quetz server to redirect all traffic to a secure endpoint.
=> feat: optionally redirect http to https

environment.yml
This PR updates the quetz dependencies and re-enables package installation from repo.mamba.pm
=> update dependencies and re-enable repo.mamba.pm 

quetz/pkgstores.py, quetz/tests/test_pkg_stores.py
If a bucket already exists `mkdir` in gscfs raises an HTTPError: "You already own this bucket.Please select another name., 409". I modified the behavior of `create_channel` to check if the bucket exists before creating it. This will usually result in the same number of API calls since most of the time the bucket will exist.
=> fix: gcs bucket exists

dev_config.toml, docs/source/deploying/authenticators.rst, docs/source/deploying/configuration.rst, quetz/authentication/auth_dao.py, quetz/authentication/base.py, quetz/authentication/github.py, quetz/authentication/gitlab.py, quetz/authentication/google.py, quetz/authentication/oauth2.py, quetz/authentication/pam.py, quetz/authentication/registry.py, quetz/config.py, quetz/dao.py, quetz/db_models.py, quetz/migrations/versions/d212023a8e0b_add_useremail_table_for_email_addresses.py, quetz/tests/authentification/test_auth_dao.py, quetz/tests/test_dao.py
This PR adds a `email` field to the User. For any kind of real-world deployment we will definitely need to collect email addresses. 
I am not sure if we should make this a opt-in feature or not ... it's "easy" to collect email adresses for Github / gitlab etc. providers, but for LDAP and others it would not be so simple.
=> start collecting email addresses for users

docs/source/deploying/configuration.rst, docs/source/using/mirroring.rst
This PR updates the documentation for channel mirroring configuration and using channel metadata to control which packages are mirrored or proxied by quetz.
=> update mirroring documentation

quetz/tasks/indexing.py
Passing large repodata files in memory is inefficient and can fail for large repodata files like conda-forge.
This PR instead uses the s3fs.put_file() to transfer the generated repodata files directly to S3.
=> upload repodata to S3 with put_file

environment.yml, quetz/dao.py, quetz/jobs/models.py, quetz/migrations/versions/794249a0b1bd_adding_jobs_tables.py, setup.cfg
Description
---
Fix compatibility with SQLAlchemy>=1.4:
- use `LargeBinary` instead of `Binary`
- also change existing `alembic` migration since `LargeBinary` is a synonym of `Binary` (deprecated since 2010 and removed in `sqlalchemy 1.4.0`, see https://github.com/sqlalchemy/sqlalchemy/issues/6263#issuecomment-819645247)
- remove upper bounds on `conda` and `pip` package deps
=> Fix compatibility with SQLAlchemy 1.4

docs/source/deploying/configuration.rst, environment.yml, quetz/config.py, quetz/pkgstores.py, setup.cfg
Addresses Issue #488.
I also bumped the requirement for gcsfs, since an [issue](https://github.com/fsspec/gcsfs/issues/448) with disabled caching was fixed in version `2022.02.0`.
=> Make cache timeout for GCS configurable

plugins/quetz_harvester/tests/conftest.py, quetz/authentication/registry.py, quetz/dao.py, quetz/db_models.py, quetz/jobs/models.py, quetz/jobs/runner.py, quetz/tasks/workers.py, quetz/testing/mockups.py, quetz/tests/api/conftest.py, quetz/tests/api/test_channels.py, quetz/tests/conftest.py, quetz/tests/test_jobs.py, quetz/tests/test_mirror.py, quetz/utils.py
This fixes a couple of pytest and sqlalchemy warnings.
=> fix some pytest and sqlalchemy warnings

docs/source/deploying/configuration.rst, environment.yml, quetz/config.py, quetz/pkgstores.py
=> Make GCS bucket location configurable

setup.cfg
httpx is actually an indirect dependency required by the authentication package
This was seen when testing the package for quetz-frontend
=> Move httpx as dependency

quetz/pkgstores.py
After providing both the keys ```Size``` and  ```size``` in S3FileSystem.info. S3Fs has switched to only providing the key [```size```]( https://github.com/fsspec/s3fs/blob/c4fb41f7cc2f2aede6bbb7755096c38b9e4cc553/s3fs/core.py#L1076) which breaks the indexing of an S3Store in quetz on newer S3Fs versions (because quetz currently uses  ```Size```).
=> Use infodata['size'] for s3fs

quetz/authentication/pam.py
=> Fix PAM authentication log message

quetz/main.py, quetz/tasks/mirror.py
@janjagusch this fixes the `noarch` issue for proxy channels and also adds the same `gzip` mechanism we use with regualr channels which should speed up repodata retrieval substantially (if you're not encoding the stream elsewhere anyways).
Let me know what you think.
=> fix proxy channels noarch and gzip repodata

quetz/tasks/indexing.py
Quetz allows to add plugins to modify the repodata info before they are written to disk or bucket.
This PR adds proper exceptions handling to log plugin exceptions and prevent cases where a plugin error causes no repodata be written to disk at all.
=> Log post_index_creation exceptions

CHANGELOG.md
Automated Changelog Entry for 0.4.4 on main
After merging this PR run the "Full Release" Workflow on your fork of `jupyter_releaser` with the following inputs
| Input  | Value |
| ------------- | ------------- |
| Target | mamba-org/quetz  |
| Branch  | main  |
| Version Spec | next |
| Since | v0.4.3 |
=> Automated Changelog Entry for 0.4.4 on main

environment.yml, plugins/quetz_tos/quetz_tos/api.py, quetz/tests/test_cli.py
=> Adds a new endpoint to check if the user already signed the TOS

quetz/tasks/indexing.py
Solution: skip non-files
fixes #540
=> channels with dots in their name cause a crash in indexing

quetz/main.py, quetz/pkgstores.py
This PR adds the api endpoint  ```/channels/{channel_name}/upload/{filename}``` to quetz. The new endpoint includes a mandatory sha256 checksum verification and uses an async ```request.stream``` that is calculating the sha256 checksum while uploading.
An example file upload for  [sqlite-3.37.2-hc67169a_0.tar.bz2](https://beta.mamba.pm/get/emscripten-forge/emscripten-32/sqlite-3.37.2-hc67169a_0.tar.bz2) with curl using the new endpoint looks like this:
```
curl -i -H  "X-API-Key: ${QUETZ_API_KEY}" \
-X POST http://127.0.0.1:8000/api/channels/uptest/upload/sqlite-3.37.2-hc67169a_0.tar.bz2?sha256=63da44f64fb627ad144d38df48b24fb741f8f787027b38219273b40ac75bada9 \
--data-binary @sqlite-3.37.2-hc67169a_0.tar.bz2
```
=> Add upload endpoint

quetz/main.py, quetz/tasks/indexing.py, quetz/tests/api/test_main_packages.py
This PR cleans the `repodata.json` files in all platforms which was containing the removed package.
Fix #475
=> Remove package from repodata.json

quetz/main.py, quetz/tests/api/test_main_packages.py
Fixes #553
Also adds a test about package name described in package itself does not match package filename.
=> Remove an uploaded package whose filename does not match the package name

quetz/cli.py, quetz/config.py, quetz/testing/fixtures.py, quetz/testing/utils.py, quetz/tests/test_cli.py, quetz/tests/test_config.py, setup.cfg
This PR should fix #459
The config file is now not mandatory, but the server will not start if one of the variables `$QUETZ_SQLALCHEMY_DATABASE_URL` and `$QUETZ_SESSION_SECRET` is missing.
The deployment directory is not mandatory either if the store is not a `LocalStore`. In fact if any other available store has a variable defined.
This also adds some basic tests to ensure server does not start without minimal settings.
**MISSING TESTS** : make sure the server starts correctly without settings file but with environment variables. Haven't found a way to kill it cleanly, so all following tests will fail with `Address already in use`.
=> no file or directory mandatory

quetz/templates/subdir-index.html.j2
Commit edaa97984bfc8c3e124efbc485e6cdec73832164 / PR #265 moved packages from the `channels/` folder to `get/`.  
However adjusting the template path was missed, so visiting the webpages that list packages result in broken links.
This PR fixes the templates, so that the links work again.
=> fix path in HTML templates

quetz/rest_models.py
fixes #563 
I added `nullable=True` to all fields specified as `Optional`.  
In `class Package` I also made a few fields `Optional` that can return `null` in practise.
=> fix OpenAPI spec. by allowing "nullable" values

quetz/cli.py, quetz/dao.py, quetz/main.py, quetz/tasks/cleanup.py, quetz/tests/api/test_main_packages.py
fixes #560 by regenerating the `package_versions` table after deleting the package
**Note:** This does NOT fix the issue where *uploading* multiple packages at once will result in inconsistent `version_order` values. 
The inconsistency is shown in the mentioned issue as well, but I'm not sure if it has any negative implications.
=> fix package_versions.version_order database field after package version deletion

.pre-commit-config.yaml, plugins/quetz_conda_suggest/quetz_conda_suggest/api.py, quetz/authentication/auth_dao.py, quetz/authentication/jupyterhub.py, quetz/dao.py, quetz/database_extensions.py, quetz/db_models.py, quetz/jobs/runner.py, quetz/main.py, quetz/tasks/indexing.py, quetz/tasks/reindexing.py, quetz/tests/test_jobs.py, quetz/tests/test_mirror.py, quetz/utils.py, quetz/versionorder.py
Follow-up from #526
* Fix missing `f` for massage strings with placeholders otherwise unresolved.
* Favor f-strings over `.format()` when sensible to do so.
* Replace %-formatting with f-strings.
=> Fix / consistent usage of f-strings

.github/workflows/ci.yml, .pre-commit-config.yaml, environment.yml, plugins/quetz_sql_authenticator/tests/test_quetz_sql_authenticator.py, plugins/quetz_tos/tests/test_quetz_tos.py, quetz/tests/api/test_channels.py, quetz/tests/api/test_main.py, quetz/tests/test_auth.py, quetz/tests/test_mirror.py, setup.cfg
This PR removes the pin on `httpx`, which was causing issues with newer versions of `starlette` which require `httpx>=0.22.0`.
See https://github.com/conda-forge/quetz-feedstock/issues/24.
- Fixed the tests which required changes to work with `httpx>=0.22.0`
- Changed plugin testing to not abort when tests have failed for one plugin
=> Remove `httpx` pin, fix tests, & test plugins individually

quetz/main.py
We need to seek to 0 to actually save the file.
Closes #590.
=> Fix upload endpoint

.github/workflows/ci.yml, plugins/quetz_conda_suggest/quetz_conda_suggest/main.py, plugins/quetz_content_trust/quetz_content_trust/db_models.py, plugins/quetz_runexports/quetz_runexports/main.py, quetz/dao.py, quetz/db_models.py, quetz/migrations/env.py, quetz/tests/test_cli.py, quetz/tests/test_jobs.py, quetz/tests/test_mirror.py
=> Make `quetz` compatible with SQLAlchemy 2.0

quetz/cli.py
Quetz prints the database connection string on startup. This is unnecessary and potentially insecure, since the person reading Quetz logs is not necessarily authorized to manage Quetz.
This patch replaces the connection string with just the name of the database engine: SQLite, PostgreSQL, or whatever happens to be preceding the first slash (useful in case the user made a typo, or other DB engines become supported in the future).
=> Avoid exposing the Postgres credentials

.coveragerc, .github/workflows/ci.yml, MANIFEST.in, mypy.ini, pyproject.toml
This PR aims to minimize the number of configuration files for the project. Instead of a separate `.coveragerc` and `mypy.ini`, we now would have all the configurations within the `pyproject.toml` file leading to a overall minimal code structure.
=> chore: move configurations to `pyproject.toml`

dev_config.toml, docs/source/deploying/configuration.rst, environment.yml, quetz/config.py, quetz/main.py, quetz/testing/fixtures.py, quetz/tests/test_profiling.py
This PR leverages `pyinstrument` to provide sampling profiling to all endpoints exposed by `quetz`.
For this to happen, the `enable_sampling` configuration of the section `profiling` must be set to `True` and then adding`profiling=true` (or any value that evaluates to `True`) as a query parameter. Once this is done, the response will not be the expected one, but an HTML view of the profiling done by `pyinstrument`.
=> Add sampler profiling

docs/source/deploying/configuration.rst, quetz/config.py, quetz/database.py
This PR adds configuration settings for the sqlalchemy pool size and overflow settings.
Additionally, the docs for the sqlalchemy configuration section are extended. While doing that, I realized that there is a setting `database_plugin_path`, which afaict [is unused](https://github.com/search?q=repo%3Amamba-org%2Fquetz+database_plugin_path&type=code). I have not removed it for now, but if anyone knows what it's about, let me know.
=> enhancement: Make sqlalchemy pool settings configurable

quetz/cli.py, quetz/database.py, quetz/tests/test_database.py
This PR adds a mechanism for sanitzing database URLs before logging them to avoid leaks of sensitive information.
Closes #630
=> enhancement: sanitize DB urls before printing

README.md, download-test-package.sh
Hey,
while checking out the development instructions for setting up a new server I realized that this command
```shell
mamba install --strict-channel-priority -c http://localhost:8000/get/channel0 -c conda-forge xtensor
```
does not work on Apple Silicon devices, since no xtensor is being downloaded.
I added an osx-arm64 version and updated the versions somewhat.
Thanks!
=> add: osx-arm64 version for testing on newer apple devices

.pre-commit-config.yaml, environment.yml, quetz/main.py, quetz/pkgstores.py, quetz/tests/test_pkg_stores.py, setup.cfg
Still a work in progress, but should be working in the local package store.
the `add_package` was not directly tested, only the `add_files`, but the upload doesn't use the `add_files`. Thus I added a very minimal test for `add_package` (with a bonus refactoring) and then went to turn it into an asynchronous function. `aiofiles` was already part of the dependencies but was never used until now, which provides a facade of synchronicity for FS local operations.
We can discuss some decisions, but first I wanted to make it work. Instead of saving the uploaded file with a random name and then renaming it, I'm writing it directly with the correct name. I tried the other way but didn't manage. Could give it another try if it's really critical.
Anyhow, would appreciate early feedback.
Edit:
I did …
=> Add async friendly upload

.github/workflows/ci.yml
In https://github.com/mamba-org/quetz/pull/636 we introduced a bug. The CI trigger `pull_request_target` runs in the context of the target repository. This means the standard checkout action uses the target repository, which breaks CI for contributions from forks.
More information on this issue here: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
Just so you know, the article strongly advises against the fix I've implemented here, as it opens the door for potential pwn requests. However, we require maintainer approval for first-time contributors before running CI, so we at least have some safe guard.
Update: I've just enabled a required maintainer approval for all outside contributros.
=> Checkout source code from fork

.pre-commit-config.yaml, quetz/authentication/oauth2.py, quetz/tests/authentification/test_oauth.py
On my machine (openSUSE Tumbleweed) `pre-commit` creates dozens of
`npm` and `pyright` processes and linting never finishes.
The latest version of `pyright-python` does not have this issue.
=> Bump pyright-python version

quetz/cli.py
`typer` 0.9.0 introduced the support for PEP-593 `Annotated` for
specifying options and argument and it is now recommended to use it:
https://typer.tiangolo.com/release-notes/#090
=> Use PEP-593 Annotated for options and arguments in CLI commands

docs/source/deploying/configuration.rst, quetz/config.py, quetz/database.py
* Pooling arguments in #632 were erroneously also propagated to sqlite engines. They should only be used if a postgres backend is used. This PR changes the propagation to fix that.
* I also reduced the default pool size from `100` to `10`, which should be much more appropriate for the typical quetz use cases, where there is no reason to maintain 100 open connections
Closes #640
=> Do not pass pooling arguments to sqlite

environment.yml
Two issues:
1. pydantic was not in our environment.yml even though we are using it directly (not just as a transitive dependency)
2. our code is currently not compatible with the recently released pydantic 2.
This PR hotfixes the dependency by down pinning it. As a follow up, we should migrate our code to be compatible with pydantic 2 in the future.
=> Pin pydantic<2

quetz/authorization.py, quetz/main.py, quetz/tests/api/test_main_packages.py
fixes #642 
- the uploader_id gets set to the user_id of the uploader when uploading package files
- in case a scoped API key is used, that user_id points to an "anonymous user"
- when listing packages, that anonymous user does not have a name (null) and provokes a crash
- when uploading through an API key, always retrieve the owner_id and use that as uploader_id
=> Fix crash when uploading a package through scoped API key

quetz/migrations/versions/3ba25f23fb7d_update_scoped_api_key_uploader_id.py
Add script to update `package_versions` uploader with API keys owner instead of the key anonymous user.
This is linked to https://github.com/mamba-org/quetz/issues/642 fixed in https://github.com/mamba-org/quetz/pull/647.
The script allows users to update existing databases automatically.
=> Add migration script for scoped API keys

quetz/main.py, quetz/tests/api/test_main_packages.py
In our deployment we have been encountering a bug that happens when:
1. a package file is uploaded through the `/upload/` route.
2. a package file with the same package version inside and the same file name, but different hashes is uploaded again.
We observe that in the second upload, we get a 409, which is good. However, we also find that the binary package file is still updated on the server, even though the http request was rejected. The repodata is not updated, as expected. This means that we get hash mismatch errors because the incorrectly updated binary does not agree with the correct hashes for the original file in the repodata.
I think the problem is [here](https://github.com/mamba-org/quetz/blob/main/quetz/main.py#L1399), where we call `pkgstore.add_package_async` before the …
=> Fix double upload bug and improve test

quetz/rest_models.py, quetz/tests/test_docs.py
In the current branch, accessing the `/docs` endpoint raises the error at the bottom of this description. It looks like a result of the change to the pydantic version.
I've added a test to check if this works correctly, but this passes even if I don't add the fix. Could find any tests where we actually run the server first, is this something that should be added?
```
uetz-web         | INFO:     192.168.128.1:52674 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
quetz-web         | ERROR:    Exception in ASGI application
quetz-web         |   + Exception Group Traceback (most recent call last):
quetz-web         |   |   File "/env/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
quetz-web         |   |     response = await …
```
=> Fix docs rest model

quetz/authorization.py, quetz/dao.py, quetz/main.py, quetz/tests/api/test_users.py
The user role `None`, indicating that the user has no permissions on the server, was accidentally removed from the data model in https://github.com/mamba-org/quetz/pull/656. This PR brings it back.
=> Fix set user roles when role is None

quetz/condainfo.py
cc @beenje do you think you could deploy a change like this?
=> ignore missing `info/files` file

environment.yml, setup.cfg
The `typer` API has changed at some point. `v0.7.0` won't work anymore but it's the version installed on a fresh development environment.
See:
```bash
File "<...>/quetz/cli.py", line 330, in <module>
path: Annotated[str, typer.Argument(help="The path of the deployment")],
TypeError: Argument() missing 1 required positional argument: 'default'
```
=> Pin `typer` to address issues in argument defaults

environment.yml, plugins/quetz_googleiap/quetz_googleiap/middleware.py, plugins/quetz_googleiap/setup.py, plugins/quetz_googleiap/tests/conftest.py, plugins/quetz_googleiap/tests/test_googleiap.py, quetz/main.py, setup.cfg
This adds a new plugin and hook for middlewares (added by plugins).
The middleware uses the headers from Google's Identity Aware Proxy to authenticate users. Furthermore, it "magically" creates a public channel per user and gives a list of pre-configured user server-owner (admin) status.
=> Add google authentication proxy middleware
