download-test-package.sh
* Remove duplicate 'wget' arg.
* Remove erroneous '.' arg.
=> Fix wget calls in download script

quetz/main.py, quetz_client/quetz_client/command_line.py, test-cli-client.sh
It may be appropriate to remove the `test-cli-client.sh` at this point, however I figured I'll just fix it for now.
=> Fix discrepancies from api endpoint change and bulk upload additions

quetz/dao_github.py, quetz/db_models.py, quetz/main.py, quetz/rest_models.py, quetz_frontend/src/components/Header.vue, static/index.html
Also detect profile changes and update the stored data as a result.
=> Handle name not being set in GitHub

quetz_client/quetz_client/command_line.py
=> client: use channel_url variable

quetz/main.py
Returns a 409 Conflict response.
=> Handle exception on attempt to upload duplicate package version

quetz_client/quetz_client/_version.py, quetz_client/quetz_client/command_line.py
* feat: add dry run option
* fix: don't run conda-verify by default, make it optional
* feat: make it possible to upload all packages from a build root
=> Client features

quetz/main.py
=> Move assert_user() call up

init_db.py, quetz/auth_github.py, quetz/cli.py, quetz/config.py, quetz/database.py, quetz/main.py
* Fix unnecessary use of f-strings
* Update config.py with a Config class
* Add support for optional sections
* Assume an entry is not required if it specifies a default
* Fix bool cast
* Explicitly check defaults for None
=> Updates to config handling

README.md, quetz/channel_data.py, quetz/condainfo.py, quetz/config.py, quetz/errors.py, quetz/indexing.py, quetz/main.py, quetz/pkgstores.py, quetz/repo_data.py, quetz/templates/channeldata-index.html.j2, quetz/templates/subdir-index.html.j2
This patch set abstracts storage methods to allow for different storage backends:
* Local filesystem
* S3
It also provides indexing (index.html generation and JSON files) on these backends, and removes the dependency on `conda index`.
=> Storage and indexing

quetz/indexing.py, quetz/templates/channeldata-index.html.j2
- Correct /index.html for subdirectories on S3
- Add missing update time information to /index.html
=> Index.html fixes

quetz/authorization.py, quetz/cli.py, quetz/main.py
Improve the test scenario:
- generate an API token randomly and print it
- associate the token with a package owner to allow force push
- allow force push for both channel and package owners
=> improve the test scenario

quetz/config.py, quetz/pkgstores.py
Fix environment variable read before set by the CLI.
Introduced in #55
=> Fix config

.flake8, .github/workflows/lint.yml, .pre-commit-config.yaml, CONTRIBUTING.md, init_db.py, pyproject.toml, quetz/auth_github.py, quetz/auth_google.py, quetz/authorization.py, quetz/channel_data.py, quetz/cli.py, quetz/condainfo.py, quetz/config.py, quetz/dao.py, quetz/dao_github.py, quetz/dao_google.py, quetz/database.py, quetz/db_models.py, quetz/errors.py, quetz/indexing.py, quetz/main.py, quetz/pkgstores.py, quetz/repo_data.py, quetz/rest_models.py, quetz_client/.flake8, quetz_client/pyproject.toml, quetz_client/quetz_client/command_line.py, quetz_client/setup.py, setup.py
Makes use of pre-commit to run `black` and `flake8` against the code base.
Adds a brief bit of documentation to `CONTRIBUTING.md` on setting up the hooks in your local repository.
=> Add github action to lint and check code formatting

quetz/cli.py, quetz/dao.py, quetz/db_models.py, quetz/main.py, quetz/rest_models.py, quetz_frontend/src/views/Packages.vue
And give the test user the full --force rights.
=> add summary to packages

quetz/cli.py, quetz/database.py, quetz/db_models.py, quetz/tests/conftest.py, quetz/tests/test_db_models.py
@wolfv , to continue the discussion about what is the best way to write tests.
Here is a very simple demo of testing `User` class in `db_models` using `pytest`.
I re-used code from [JHub tests](https://github.com/jupyterhub/jupyterhub/tree/master/jupyterhub/tests) and I'm clearly wondering how to re-use more code from this project.
Also in this PR:
- simplify the database creation
- add find method for User
- refactor cli according to changes
=> Init testing using pytest

README.md
Hi @wolfv --
This is my attempt at documenting the steps I needed to take to generate an API key for my user. Thoughts?
E
=> Add instructions for creating a channel and generating an API key

quetz/config.py, quetz/pkgstores.py
Relatively small change that allows for using IAM roles instead of access keys to make use of the s3 backend
=> Update s3 backend to allow for IAM

quetz/dao.py, quetz/db_models.py, quetz/main.py, quetz/mirror.py, quetz/rest_models.py, quetz/tests/test_mirror.py
implementation of the mirror channels (aka "mirror"-mode)
good to merge @wolfv
=> Mirror mode

quetz/dao.py, quetz/main.py, quetz/tests/conftest.py, quetz/tests/test_main.py, quetz/tests/test_mirror.py
this is a preparation for implementing changelog
=> query package version by upload time

README.md
and some small edits in the mirror sections of README
=> add instructions for mirror synchronisation

README.md
=> fix mirror channel name in README

.github/workflows/ci.yml, README.md, dev_config.toml, quetz/channel_data.py, quetz/dao.py, quetz/database.py, quetz/db_models.py, quetz/tests/conftest.py, quetz/tests/test_auth.py, quetz/tests/test_db_models.py, quetz/tests/test_mirror.py
fix schemas and tests to make quetz and the tests run with postgres db
running with postgres  fixes the problem of segfaults when adding multiple versions of the same package (issue #118)
also add postgres-based tests to the build matrix on CI
=> fix postgres compatibility issues

quetz/main.py, quetz_client/quetz_client/command_line.py, quetz_frontend/src/components/Header.vue, quetz_frontend/src/router.js, quetz_frontend/src/views/ApiKeys.vue, quetz_frontend/vue.config.js
This adds a basic frontend for api key handling.
=> add api key handling to quetz-client, and api keys frontend

MANIFEST.in, quetz_client/quetz_client/command_line.py
Properly install templates into pip package and some stuff in the cli client.
=> add templates to manifest and add create_channels to client

.github/workflows/ci.yml, plugins/quetz_repodata_patching/README.md, plugins/quetz_repodata_patching/quetz_repodata_patching/main.py, plugins/quetz_repodata_patching/setup.py, plugins/quetz_repodata_patching/tests/conftest.py, plugins/quetz_repodata_patching/tests/test_main.py, quetz/config.py, quetz/hooks.py, quetz/indexing.py, quetz/main.py, quetz/testing/fixtures.py, quetz/tests/conftest.py
Links:
- https://docs.conda.io/projects/conda-build/en/latest/concepts/generating-index.html#repodata-patching
- https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/13#issuecomment-608118681
- https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/master/recipe
Reference implementation:
- https://github.com/conda/conda-build/blob/7429f8e36caed54ce30892c17711b18339d24ae0/conda_build/index.py#L826
TODO:
=> Repodata patching

quetz/config.py, quetz/deps.py
fixes #140
largely based on: https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/#combining-timeouts-and-retries
=> adding timeouts and retries to mirror server requests

quetz/indexing.py, quetz/mirror.py
=> update only modified subdirs

docs/source/configuration.rst, docs/source/qeps/qep-001-user-permissions.rst, plugins/quetz_conda_suggest/quetz_conda_suggest/main.py, plugins/quetz_conda_suggest/tests/test_quetz_conda_suggest.py, plugins/quetz_repodata_patching/quetz_repodata_patching/main.py, plugins/quetz_repodata_patching/tests/test_main.py, plugins/quetz_runexports/quetz_runexports/main.py, plugins/quetz_runexports/tests/test_quetz_runexports.py, quetz/auth_github.py, quetz/authorization.py, quetz/cli.py, quetz/config.py, quetz/dao.py, quetz/dao_github.py, quetz/deps.py, quetz/main.py, quetz/testing/fixtures.py, quetz/tests/conftest.py, quetz/tests/test_auth_github.py, quetz/tests/test_cli.py, quetz/tests/test_config.py, quetz/tests/test_dao.py, quetz/tests/test_github_dao.py, quetz/tests/test_main.py
implementation of [QEP1](https://quetz.readthedocs.io/en/latest/qeps/qep-001-user-permissions.html) (part 2)
=> add users section to config

quetz/dao.py, quetz/main.py, quetz/tests/test_main.py
fixes the bug introduced in #147
=> fix listing users without profile

CONTRIBUTING.md, docs/source/deploying/configuration.rst, docs/source/deploying/database.rst, docs/source/deploying/frontend.rst, docs/source/deploying/index.rst, docs/source/index.rst, docs/source/using/basics.rst, docs/source/using/index.rst, docs/source/using/mirroring.rst
adding sections from the readme file:
* deploying
- database
- fronted
* using:
- creating channels/api keys
- mirroring
etc
=> Add sections to docs

quetz/authorization.py, quetz/main.py, quetz/tests/test_main.py
=> check permissions when creating a package

quetz/authorization.py, quetz/dao.py, quetz/main.py, quetz/tests/test_main.py
=> check permissions to list channel members

quetz/condainfo.py, quetz/exceptions.py, quetz/main.py, quetz/tests/test_main.py
=> handle errors in package format in condainfo

.github/workflows/ci.yml, quetz/tests/test_auth.py, quetz/tests/test_mirror.py
CI would not fail if only one of the testing commands fails
also fixing some failing tests
=> update  CI workflow

quetz/dao.py, quetz/database.py, quetz/db_models.py, quetz/testing/fixtures.py, quetz/tests/test_main.py, quetz/tests/test_versionorder.py, quetz/versionorder.py
This is adding in the necessities for ordering versions according to conda's specs.
I am going to work on adding a sort-field in the database now.
=> Version Order code

quetz/dao.py
Fix for concurrent write in package_versions table.
This PR passes the concurrency test in https://gist.github.com/btel/a808d8ef4a6a868a1c952805a0e453f8 with postgresql
Fails for sqlite.
=> add locking for postgres

quetz/condainfo.py
this PR fixes synchronisation with my anaconda.org [channel](https://anaconda.org/btel):
```
curl -X POST "http://localhost:8000/api/channels" \
-H  "accept: application/json" \
-H  "Content-Type: application/json" \
-H  "X-API-Key: ${QUETZ_API_KEY}" \
-d '{"name":"mirror-channel",
"private":false,
"mirror_channel_url":"https://conda.anaconda.org/btel",
"mirror_mode":"mirror"}'
```
this channel contains [nrnpython](https://anaconda.org/btel/nrnpython) package, which does not have all the metadata extracted by CondaInfo, and also does not provide `subdir` in `info/index.json`
=> condainfo compat with old package format

.github/workflows/ci.yml, README.md, plugins/quetz_conda_suggest/tests/test_quetz_conda_suggest.py, plugins/quetz_runexports/tests/test_quetz_runexports.py, quetz/authorization.py, quetz/db_models.py, quetz/deps.py, quetz/main.py, quetz/rest_models.py, quetz/tasks/common.py, quetz/tasks/indexing.py, quetz/tasks/reindexing.py, quetz/tasks/workers.py, quetz/testing/fixtures.py, quetz/tests/test_mirror.py, quetz/tests/test_tasks.py, quetz/tests/test_workers.py, setup.py
* implementation of worker launching tasks in sub-processes
* adds unit tests for workers
* refactors worker class
* adds dependency on starlette-full
* fixes issues with testing postgres, where it might fail silently
* disables unused plugins for testing which avoids db consistency issues with postgres
=> Subprocess worker

.github/workflows/ci.yml, docs/source/deploying/configuration.rst, quetz/authorization.py, quetz/dao.py, quetz/main.py, quetz/pkgstores.py, quetz/tests/test_main.py, quetz/tests/test_pkg_stores.py
To run the s3 tests on github CI add the `S3_ACCESS_KEY` and `S3_SECRET_KEY` secrets to the mamba-org/quetz repo (will run on ovh s3).
=> channel delete endpoint

.github/workflows/ci.yml, .github/workflows/mypy.yml, README.md, environment.yml
use the same dependencies from environment.yml file across the project:
=> install requirements from file on CI

.github/workflows/ci.yml, quetz/deps.py, quetz/tasks/workers.py, quetz/testing/fixtures.py, quetz/tests/test_workers.py
For some reason, the tests fail. But, do these changes suffice for adding the test? What about the `async` and `await` keywords? Are they applicable here? CC: @btel @wolfv 
Also, they won't run on CI for now. So the above comment was for failing locally.
=> add tests for redis

quetz/config.py, quetz/tasks/mirror.py
@btel let me know what you think
=> use fingerprints from database when mirror syncing

.github/workflows/ci.yml, environment.yml, quetz/deps.py, quetz/tasks/workers.py
Fixes https://github.com/mamba-org/quetz/issues/201
=> make redis-py and rq optional

quetz/main.py, quetz/pkgstores.py
this should fix issues with downloading static files
=> iterate files in chunks

quetz/authorization.py, quetz/dao.py, quetz/main.py, quetz/tests/api/test_api_keys.py, quetz/tests/test_auth.py
flag api as deleted and make sure it can't be used for authentification
=> Delete api keys

plugins/quetz_repodata_patching/quetz_repodata_patching/main.py
Fixes https://github.com/mamba-org/quetz/issues/186
=> add tryfirst for repodata-patching

quetz/config.py, quetz/testing/fixtures.py, quetz/tests/test_cli.py, quetz/tests/test_config.py
Fixes https://github.com/mamba-org/quetz/issues/197
=> ask user to set the QUETZ_CONFIG_FILE environment variable

quetz/dao.py, quetz/main.py, quetz/tests/api/test_api_keys.py
related to #134 
also removes deleted api keys from the list.
=> fix listing api keys

plugins/quetz_transmutation/tests/test_main.py, quetz/jobs/runner.py, quetz/tests/test_jobs.py
* empty package_spec  returns no results
* wildcard spec `*` returns all packages
* globbing pattern `my-*` returns partial match
=> Wildcard in package names

quetz/dao.py, quetz/main.py, quetz/rest_models.py, quetz/tests/test_auth.py, quetz/utils.py
Linting would probably fail because the regex is long. And changing it so that it is multiple lines kind of changes the regex if I recall correctly. So this can be ignored for now.
=> add github style search for Packages

quetz/frontend.py
Python backend to pass data for which login is available
=> dynamically add login buttons

plugins/quetz_conda_suggest/tests/conftest.py, plugins/quetz_conda_suggest/tests/test_quetz_conda_suggest.py, plugins/quetz_current_repodata/tests/conftest.py, plugins/quetz_current_repodata/tests/test_current_repodata.py, quetz/frontend.py
Python backend to remove flashing while logging.
=> remove flashing user

plugins/quetz_conda_suggest/tests/conftest.py, plugins/quetz_conda_suggest/tests/test_quetz_conda_suggest.py, plugins/quetz_current_repodata/tests/conftest.py, plugins/quetz_runexports/tests/conftest.py, quetz/dao.py, quetz/tests/api/test_channels.py, quetz/tests/test_auth_github.py, quetz/tests/test_dao.py, quetz/tests/test_mirror.py
Fixes https://github.com/mamba-org/quetz/issues/279
=> do not allow _ in channel names

quetz/main.py
Fixes https://github.com/mamba-org/quetz/issues/101
=> create channel in pkgstore upon creation

quetz/authorization.py, quetz/dao.py, quetz/main.py, quetz/rest_models.py, quetz/tests/api/test_channels.py, quetz/tests/api/test_users.py
adds enpoints:
-  `/api/users/{}/channels`
-  `/api/paginated/users/{}/channels`
=> List user channels

quetz/dao.py, quetz/main.py, quetz/rest_models.py, quetz/tests/api/test_users.py
adds enpoints:
-  `/api/users/{}/packages`
-  `/api/paginated/users/{}/packages`
=> list user packages

quetz/dao.py, quetz/jobs/api.py, quetz/tests/test_jobs.py
=> filter and paginate tasks

quetz/pkgstores.py
fixes https://github.com/mamba-org/quetz/issues/325
=> fix delete file interface

quetz/authorization.py, quetz/channel_data.py, quetz/tests/test_auth.py
and allow API keys without expiry
closes #343
=> Remove dep conda build

quetz/pkgstores.py
i am not sure why the s3 tests fail on master, but I blame the caches
=> fix s3 tests

quetz/main.py, quetz/pkgstores.py, quetz/tests/test_pkg_stores.py
=> Remove channels recursively

quetz/tasks/mirror.py, quetz/tests/test_mirror.py
=> fix conda info with repodata sync

quetz/tasks/indexing.py, quetz/tests/test_indexing.py, quetz/tests/test_pkg_stores.py
=> Move temporary index files

quetz/deps.py, quetz/tasks/workers.py, quetz/testing/fixtures.py
=> create new sqlite connection in threads

docs/source/using/mirroring.rst
=> update mirroring docs

quetz/cli.py, quetz/config.py, quetz/deps.py, quetz/jobs/dao.py, quetz/jobs/models.py, quetz/jobs/runner.py, quetz/migrations/versions/0a0ab48887ab_adding_function_args_to_job_spec.py, quetz/tasks/common.py, quetz/tasks/workers.py, quetz/testing/mockups.py, quetz/tests/api/test_channels.py, quetz/tests/test_jobs.py, quetz/tests/test_mirror.py, quetz/tests/test_workers.py
=> Dispatch actions from supervisor

docker/nginx.conf, docs/source/deploying/nginx.rst, quetz/config.py, quetz/pkgstores.py
@beenje would be interested in your feedback here.
=> add redirect to nginx with secure link

.gitignore, environment.yml, quetz/authentication/azuread.py, quetz/basic_frontend/index.html, quetz/config.py, quetz/main.py, quetz/tests/authentification/test_oauth.py
This PR implements an AzureAD authenticator for Quetz.
=> Implements an AzureAD authenticator for Quetz

quetz/jobs/runner.py, quetz/tasks/indexing.py
Description
---
Remove useless logs:
- do not log when there is no pending job/task
- change log level to debug for moving a file during indexing, the info level is index creation (not file creation/copy/etc.)
=> Remove useless logs

quetz/config.py
Closes #516 
Admittedly I didn't test this, but I'm fairly sure this should make the GCS config work again.
Having another patch release would be very appreciated! 🙏
=> Fix gcs region config entry

quetz/main.py, quetz/utils.py
=> log errors of background tasks

README.md
It might be useful to advertise the existence of the prebuilt image. Feel free to take it or leave it if you don't think it's worthwhile.
=> Add docker badge to README

.readthedocs.yml
=> Fix ReadTheDocs

.readthedocs.yml
Config taken straight from the docs: https://docs.readthedocs.io/en/stable/guides/conda.html#id1
=> Try to fix ReadTheDocs 2

quetz/authentication/oauth2.py
=> Cast starlette URL to str

quetz/main.py, quetz/tests/api/test_main_packages.py
We currently have two very similar file upload routes:
1. `/channels/{channel_name}/packages/{package_name}/files/` (`post_file_to_package`)
2. `/channels/{channel_name}/upload/{file_name}` (`post_upload`)
The first one is currently well-tested, but the latter is not. This PR updates the testing so that more similar tests are applied to both routes. While doing this, I found that the second route does not check if uploaded file and package names are consistent, which the former route does. I also made this consistent now.
=> Make upload routes consistent with each other
